# Generated by Django 3.2.2 on 2021-05-29 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('get_water_info', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='analysisdata',
            old_name='f_id',
            new_name='member_id',
        ),
    ]
