# Generated by Django 3.2.2 on 2021-06-01 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('get_water_info', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysisdata',
            name='latitude',
            field=models.FloatField(verbose_name='위도'),
        ),
        migrations.AlterField(
            model_name='analysisdata',
            name='longitude',
            field=models.FloatField(verbose_name='경도'),
        ),
    ]
