# Generated by Django 3.2.2 on 2021-06-05 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('get_water_info', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysisdata',
            name='public_ph',
            field=models.FloatField(default=7.048, verbose_name='공공데이터_pH'),
        ),
        migrations.AlterField(
            model_name='analysisdata',
            name='public_rc',
            field=models.FloatField(default=0.32, verbose_name='공공데이터_잔류염소'),
        ),
        migrations.AlterField(
            model_name='analysisdata',
            name='public_tb',
            field=models.FloatField(default=0.063, verbose_name='공공데이터_탁도'),
        ),
    ]
