# Generated by Django 3.2.2 on 2021-06-02 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('get_water_info', '0002_auto_20210601_2320'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisdata',
            name='filename',
            field=models.CharField(default='', max_length=254, verbose_name='파일명'),
            preserve_default=False,
        ),
    ]
