# Generated by Django 3.2.2 on 2021-06-04 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('get_water_info', '0003_analysisdata_filename'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisdata',
            name='public_ph',
            field=models.FloatField(default=6.911, verbose_name='공공데이터_pH'),
        ),
        migrations.AddField(
            model_name='analysisdata',
            name='public_rc',
            field=models.FloatField(default=3.589, verbose_name='공공데이터_잔류염소'),
        ),
        migrations.AddField(
            model_name='analysisdata',
            name='public_tb',
            field=models.FloatField(default=0.067, verbose_name='공공데이터_탁도'),
        ),
    ]
