# Generated by Django 3.2.2 on 2021-05-11 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('name', models.CharField(max_length=32, verbose_name='성명')),
                ('email', models.CharField(max_length=32, unique=True, verbose_name='이메일')),
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False, unique=True, verbose_name='아이디')),
                ('pw', models.CharField(max_length=32, verbose_name='비밀번호')),
            ],
            options={
                'verbose_name': '사용자',
                'verbose_name_plural': '사용자',
                'db_table': 'member',
            },
        ),
    ]
