# Generated by Django 3.2.2 on 2021-05-15 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='이름')),
                ('phone', models.CharField(max_length=32, verbose_name='연락처')),
                ('email', models.EmailField(max_length=254, verbose_name='이메일')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('usage', models.IntegerField()),
                ('num_people', models.IntegerField()),
            ],
            options={
                'verbose_name': '분석 요청',
                'verbose_name_plural': '분석 요청',
                'db_table': 'AnalysisRequest',
            },
        ),
    ]
