# Generated by Django 3.2.2 on 2021-05-29 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('water_req', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysisrequest',
            name='end_date',
            field=models.CharField(max_length=32, null=True, verbose_name='종료 날짜'),
        ),
        migrations.AlterField(
            model_name='analysisrequest',
            name='request_date',
            field=models.CharField(max_length=32, primary_key=True, serialize=False, unique=True, verbose_name='요청날짜'),
        ),
        migrations.AlterField(
            model_name='analysisrequest',
            name='start_date',
            field=models.CharField(max_length=32, null=True, verbose_name='시작 날짜'),
        ),
    ]
