# Generated by Django 3.2.2 on 2021-05-15 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('water_req', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analysisrequest',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='analysisrequest',
            name='num_people',
        ),
        migrations.RemoveField(
            model_name='analysisrequest',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='analysisrequest',
            name='usage',
        ),
    ]
